server:
  port: 8188
  
# Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
  # JPA Setting
  jpa:
    show-sql: true
    # Operation -> create / none
    hibernate:
      ddl-auto: update
      
  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: syr961220@gmail.com
    password: gzeh ogxa jqyi nsxg
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
      
      
#Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
  
logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL